<div class="information-details">
    <div class="alert alert-danger margin-top text-center">
        DAS WETTEN AUF SPIELE IST AUSDRÜCKLICH VERBOTEN!
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Money matches</strong>
        </div>
        <div class="col-md-8">
            <p>Jeder ab 18 Jahren hat die Möglichkeit sich für ein oder mehrere „Gambling-Matches“ beim Organisations-Team anzumelden.</p>
            <p>Jeder kann Jeden fordern.</p>
            <p>Geldeinsätze die ausgespielt werden, können beim Organisations-Team hinterlegt werden.</p>
            <p>Winner takes it all.</p>
            <p>Alle „Spielregeln“ können vorher ausgemacht und schriftlich festgehalten werden.</p>
            <p>Es kann eine realistische Vorgabe ausgemacht werden.</p>
            <p>Doppel- oder Teammatches sind ebenfalls möglich.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>10-Ball Winner-stays-table</strong>
        </div>
        <div class="col-md-8">
            <p>Ein 10 Ball Spiel um 5, 10 oder 20 € (wird durch das Organisations-Team festgelegt).</p>
            <p>Geldauszahlung nach jedem Spiel.</p>
            <p>Gewinner bleibt am Tisch und hat Anstoß im nächsten Spiel.</p>
            <p>Man kann sich immer wieder auf die Spielliste eintragen lassen.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Winner takes it all - Turnier</strong>
        </div>
        <div class="col-md-8">
            Finden sich 8 Spieler, die ein Turnier (Einfach-KO) spielen wollen, wird ein Startgeld (20, 50 oder 100 €) vereinbart und los geht’s.
        </div>
    </div>
    <div class="alert alert-danger margin-top text-center">
        DAS WETTEN AUF SPIELE IST AUSDRÜCKLICH VERBOTEN!
    </div>
</div>
