<div class="information-details">
    <div class="alert alert-danger margin-top text-center">
        BETTING ON THE GAMES IS NOT ALLOWED!
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Money matches:</strong>
        </div>
        <div class="col-md-8">
            <p>On Friday and Saturday after 6 pm</p>
            <p>Everyone older than 18 can register for one or more "money matches" at the organisation team.</p>
            <p>Everyone can challenge matches.</p>
            <p>Money payouts can be deposited at the organisation team</p>
            <p>The winner takes it all.</p>
            <p>Individual game rules (or realistic handicap) can be arranged and written down at the organisation team.</p>
            <p>Doubles or team matches are possible.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>10-Ball Winner-stays-table:</strong>
        </div>
        <div class="col-md-8">
            <p>Entry fee € 5, 10 or 20 (will be determined by organisation team).</p>
            <p>Cash payouts after each rack.</p>
            <p>Winner stays at the table and has the break in the next rack.</p>
            <p>Every player can request a wait list position.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Winner takes it all - Tournament:</strong>
        </div>
        <div class="col-md-8">
            If 8 players decide a winner takes all tournament (single elimination), they just have to agree the entry fee (€ 20, 50 or 100) and start.
        </div>
    </div>
    <div class="alert alert-danger margin-top text-center">
        BETTING ON THE GAMES IS NOT ALLOWED!
    </div>
</div>
