<?php
$navigation = [
    'info' => [
        'main_tournament',
        'wcop',
        'gambling'
    ],
    'participants' => [
        'main_tournament',
        'seeded',
        'wcop'
    ],
    'results' => [
        'friday',
        'saturday',
        'sunday',
        'wcop',
        'gambling'
    ],
    'registration',
    'gallery' => [
        'previous_2013',
        'venue',
        'friday',
        'saturday',
        'sunday'
    ],
    'sponsors',
    'contact'
]
?>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div id="languages" data-role="languages" class="pull-left">
            <a data-url="en" href="?lang=en"><span class="glyphicon bfh-flag-GB">&nbsp;</span>EN</a>
            <a data-url="de" href="?lang=de"><span class="glyphicon bfh-flag-DE">&nbsp;</span>DE</a>
        </div>
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <? foreach ($navigation as $key => $value) : ?>
                    <? if(is_array($value)) : ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <b><?=translate('nav.' . $key)?></b> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?foreach ($value as $submenu) : ?>
                                    <li><a href="?section=<?=$key?>&tab=<?=$submenu?>"><b><?=translate('nav.' . $submenu)?></b></a></li>
                                <?endforeach?>
                            </ul>
                        </li>
                    <? else : ?>
                        <li><a href="?section=<?=$value?>"><b><?=translate('nav.' . $value)?></b></a></li>
                    <? endif?>
                <? endforeach ?>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
