<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <div id="languages">
                <a href="?lang=en">EN</a>
                <a href="?lang=de">DE</a>
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a href="?section=participants"><?=translate('nav.participants')?></a>
                </li>
                <li>
                    <a href="?section=results"><?=translate('nav.results')?></a>
                </li>
                <li>
                    <a href="?section=registration"><?=translate('nav.registration')?></a>
                </li>
                <li>
                    <a href="?section=gallery"><?=translate('nav.gallery')?></a>
                </li>
                <li>
                    <a href="?section=team"><?=translate('nav.team')?></a>
                </li>
                <li>
                    <a href="#sponsors"><?=translate('nav.sponsors')?></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
