<?php
$navigation = [
    'info' => [
        'main_tournament',
        'wcop',
        'gambling'
    ],
    'participants' => [
        'friday',
        'saturday',
        'seeded'
    ],
    'results' => [
        'friday',
        'saturday',
        'sunday',
        'wcop'
    ],
    'registration',
    'gallery' => [
        'previous_2013',
        'friday',
        'saturday',
        'sunday'
    ],
    'hotels',
    'sponsors',
    'contact'
]
?>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <a href="?section=index" class="navbar-brand">
            <img width="50" src="assets/img/icons/logo.jpg" alt="Action Days" class="pull-left">
            <div class="text-center pull-left">
                <span>Action Days</span>
                <p class="brand-extension-text">by Playhouse FFB</p>
            </div>
        </a>
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <? foreach ($navigation as $key => $value) : ?>
                    <? if(is_array($value)) : ?>
                        <li class="dropdown">
                            <a href="?section=<?=$key?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <b><?=translate('nav.' . $key)?></b> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?foreach ($value as $submenu) : ?>
                                    <li><a href="?section=<?=$key?>&tab=<?=$submenu?>"><b><?=translate('nav.' . $submenu)?></b></a></li>
                                <?endforeach?>
                            </ul>
                        </li>
                    <? else : ?>
                        <li><a href="?section=<?=$value?>"><b><?=translate('nav.' . $value)?></b></a></li>
                    <? endif?>
                <? endforeach ?>
                <? $activeLang = $GLOBALS['locale']?>
                <? $langs = [
                    'de' => 'bfh-flag-DE',
                    'en' => 'bfh-flag-GB'
                ]?>
                <li class="dropdown">
                    <a data-url="<?=$activeLang?>" href="?lang=<?=$activeLang?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <span class="glyphicon <?=$langs[$activeLang]?>">&nbsp;</span>
                        <b><?=mb_strtoupper($activeLang)?></b> <span class="caret">
                    </a>
                    <ul class="dropdown-menu" role="menu" data-role="languages">
                        <li><a data-url="en" href="?lang=en"><span class="glyphicon bfh-flag-GB">&nbsp;</span><b>EN</b></a></li>
                        <li><a data-url="de" href="?lang=de"><span class="glyphicon bfh-flag-DE">&nbsp;</span><b>DE</b></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
