<h3 class="text-center blue-text margin-bottom">Playhouse 10 Ball Nation Cup</h3>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <iframe width="100%" height="300"
                src="https://www.youtube.com/embed/4uSVv9GijXg"
                frameborder="0"
                allowfullscreen>
        </iframe>
    </div>
</div>
<? include("wcop/participants.phtml") ?>
<? include("wcop/{$GLOBALS['locale']}.phtml") ?>

<div class="row">
    <div class="form-group col-md-12 margin-top">
        <a href="?section=results&tab=wcop" class="col-xs-12 col-md-4 pull-right btn btn-blue"><?=translate('button.draw_and_results')?><i class="fa fa-chevron-right"></i></a>
    </div>
</div>
