<h3 class="text-center blue-text margin-bottom">Playhouse 10 Ball Nation Cup</h3>
<? include("wcop/participants.phtml") ?>
<? include("wcop/{$GLOBALS['locale']}.phtml") ?>

<div class="row">
    <div class="form-group col-md-12 margin-top">
        <a href="?section=results&tab=wcop" class="col-xs-12 col-md-4 pull-right btn btn-blue"><?=translate('button.draw_and_results')?><i class="fa fa-chevron-right"></i></a>
    </div>
</div>
