<section id="contact">
    <div class="container content text-center">
        <h2><?=translate('contact.title')?></h2>
        <hr class="colored">
        <div class="row" style="margin-top: 50px">
            <div class="col-md-6 col-sm-6">
                <!-- Google Map -->
                <div id="map"></div>
                <!-- End Google Map -->
            </div>
            <div class="col-md-6 col-sm-6 text-left">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <img width="100%" src="<?=IMG_PATH?>/sponsors/Playhouse.png" />
                    </div>
                    <div class="col-md-6">
                        <p><i class="fa fa-home"></i> Hasenheide 6, <br>82256 Fürstenfeldbruck, <br>Germany</p>
                        <p><i class="fa fa-clock-o"></i> <?=translate('contact.business_hours.title')?>:<br>
                        <?=translate('contact.business_hours.content')?></p>
                    </div>
                    <div class="col-md-6">
                        <p><i class="fa fa-envelope"></i> info@action-days.de</p>
                        <p><i class="fa fa-phone"></i> 0049 172 7009969</p>
                        <p><a href="http://www.playhouse-ffb.de/" target="_blank"><i class="fa fa-globe"></i> www.playhouse-ffb.de</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>
    function init_map() {
        var var_location = new google.maps.LatLng(48.194999, 11.249539);

        var var_mapoptions = {
            center: var_location,
            zoom: 14
        };

        var var_marker = new google.maps.Marker({
            position: var_location,
            map: var_map,
            title:"Playhouse Fürstenfeldbruck"});

        var var_map = new google.maps.Map(document.getElementById("map"),
            var_mapoptions);

        var_marker.setMap(var_map);

    }
    google.maps.event.addDomListener(window, 'load', init_map);
</script>
