<section id="contact">
    <div class="container content text-center">
        <h2><?=translate('contact.title')?></h2>
        <hr class="colored">
        <div class="row" style="margin-top: 50px">
            <div class="col-md-6 col-sm-6">
                <!-- Google Map -->
                <div id="map"></div>
                <!-- End Google Map -->
            </div>
            <div class="col-md-6 col-sm-6 text-left">

                <!-- Contacts -->
                <h3><?=translate('contact.venue.title')?></h3>
                <ul class="list-unstyled venue">
                    <li><i class="fa fa-home"></i> Hasenheide 6, 82256 Fürstenfeldbruck, Germany</li>
                    <li><a href="mailto:info@action-days.de"><i class="fa fa-envelope"></i> info@action-days.de</a></li>
                    <li><a href="tel:"><i class="fa fa-phone"></i> 1(222) 5x86 x97x</a></li>
                    <li><a href="http://www.playhouse-ffb.de/" target="_blank"><i class="fa fa-globe"></i> http://www.playhouse-ffb.de/</a></li>
                </ul>

                <hr>

                <!-- Business Hours -->
                <h3><?=translate('contact.business_hours.title')?></h3>
                <ul class="list-unstyled">
                    <li><?=translate('contact.business_hours.content')?></li>
                </ul>
            </div>
        </div>
    </div>
</section>
