<?php
$tabs = $data['tabs'];
$activeTab =$data['activeTab'];

$folder = IMG_PATH . "gallery/{$activeTab}/";
$filetype = '*.*';
$files = glob($folder.$filetype);
$filenames = [];
foreach ($files as $file) {
    $pathinfo = pathinfo($file);
    $filenames[$pathinfo['filename']] = "assets/img/gallery/{$activeTab}/{$pathinfo['basename']}";
}
?>
<section id="gallery">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('gallery.title')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <div class="portfolio-filter">
                    <ul id="filters" class="clearfix">
                        <? foreach ($tabs as $name => $tab) : ?>
                            <li>
                                <a href="?section=gallery&tab=<?=$name?>">
                                    <span class="filter<?=$activeTab == $name ? ' active' : ''?>" data-filter="<?=$name?>">
                                        <?=translate('tab.' . $name)?>
                                    </span>
                                </a>
                            </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="sliderlist">
            <div class="content active" data-cat="<?=$activeTab?>" data-toggle="modal">
                <? if (!empty($filenames)) : ?>
                    <div id="galleryContainer" >
                        <? foreach ($filenames as $name => $path) : ?>
                            <a href="<?=$path?>">
                                <img alt="<?=$name?>" src="<?=$path?>" />
                            </a>
                        <? endforeach ?>
                    </div>
                <? else : ?>
                    <? include ('partials/p_comming_soon.phtml')?>
                <? endif ?>
            </div>
        </div>
    </div>
</section>
