<?php
$tabs = $data['tabs'];
$activeTab =$data['activeTab'];

$folder = IMG_PATH . "gallery/{$activeTab}/";
$filetype = '*.*';
$files = glob($folder.$filetype);
$filenames = [];
if (!empty($files)) {
    foreach ($files as $file) {
        $pathinfo = pathinfo($file);
        $filenames[$pathinfo['filename']] = "assets/img/gallery/{$activeTab}/{$pathinfo['basename']}";
    }
}
?>
<section id="gallery">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('gallery.title')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <div class="portfolio-filter">
                    <ul id="filters" class="clearfix">
                        <? foreach ($tabs as $name => $tab) : ?>
                            <li>
                                <a href="?section=gallery&tab=<?=$name?>">
                                    <span class="filter<?=$activeTab == $name ? ' active' : ''?>" data-filter="<?=$name?>">
                                        <?=translate('tab.' . $name)?>
                                    </span>
                                </a>
                            </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="sliderlist">
            <div class="content active" data-cat="<?=$activeTab?>" data-toggle="modal">
                <?if($activeTab == 'videos_2013'):?>
                    <? include("gallery/videos_2013.phtml") ?>
                <?else:?>
                    <? if (!empty($filenames)) : ?>
                        <div id="galleryContainer" >
                            <? foreach ($filenames as $name => $path) : ?>
                                <a href="<?=$path?>">
                                    <img alt="Action Days 2013" src="<?="assets/img/gallery/{$activeTab}/thumbnails/{$name}.jpg"?>" />
                                </a>
                            <? endforeach ?>
                        </div>
                    <? else : ?>
                        <? include ('partials/p_comming_soon.phtml')?>
                    <? endif ?>
                <?endif?>
            </div>
        </div>
    </div>
</section>
