
<section id="error">
    <div class="container text-center">
        <h3><?=translate('error.title')?></h3>
        <hr class="colored">
        <div class="row commingsoon">
            <div class="col-md-12">
                <a href="/index.php">
                    <h2 class="caption blue-text"><?=translate('link.to.homepage')?></h2>
                    <img  width="100%" src="<?=IMG_PATH . 'bg_arena_sw.jpg'?>"/>
                </a>
            </div>
    </div>
</section>

