<?php
$pathToSliderImages = IMG_PATH . 'index/carousel/';
$carouselId = 'homePageCarousel';
$carouselItems = [
    [
        'imgUrl' => $pathToSliderImages . 'arena.jpg',
        'captionHeader' => translate('index.carousel.caption.header.arena'),
        'captionText' => translate('index.carousel.caption.text.arena'),
    ],
    [
        'imgUrl' => $pathToSliderImages . 'hundal_hybler.jpg',
        'captionHeader' => translate('index.carousel.caption.header.hundal_hybler'),
        'captionText' => translate('index.carousel.caption.text.hundal_hybler'),
    ],
    [
        'imgUrl' => $pathToSliderImages . 'gambling.jpg',
        'captionHeader' => translate('index.carousel.caption.header.gambling'),
        'captionText' => translate('index.carousel.caption.text.gambling'),
    ],
    [
        'imgUrl' => $pathToSliderImages . 'mosconi_cup.jpg',
        'captionHeader' => translate('index.carousel.caption.header.mosconi_cup'),
        'captionText' => translate('index.carousel.caption.text.mosconi_cup'),
    ],
    [
        'imgUrl' => $pathToSliderImages . 'winner2013.jpg',
        'captionHeader' => translate('index.carousel.caption.header.winner2013'),
        'captionText' => translate('index.carousel.caption.text.winner2013'),
    ],
]
?>

<section id="homepage">
    <div class="container content text-left">
        <div class="title text-center">
            <div class="title-caption">Welcome to</div>
            <h2> 2nd Playhouse Actiondays</h2>
            <p>1 - 3 Mai 2015, Fürstenfeldbruck (<?=translate('country.de')?>)</p>
            <hr class="colored">
            <h3 class="blue-text"><?=translate('homepage.header.subtitle')?></h3>
            <hr class="colored">
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7">
                <div id="<?=$carouselId?>" class="carousel slide margin-bottom" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <? for ($i=0; $i<count($carouselItems); $i++) : ?>
                            <li data-target="<?=$carouselId?>" data-slide-to="<?=$i?>" <?=$i==0 ? 'class="active"' : '' ?>></li>
                        <? endfor ?>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <? foreach ($carouselItems as $index => $item) : ?>
                            <div class="item <?=$index == 0 ? 'active' : ''?>">
                                <img height="" src="<?=$item['imgUrl']?>" alt="<?=$item['captionHeader']?>">
                                <div class="carousel-caption">
                                    <h3><?=$item['captionHeader']?></h3>
                                    <p><?=$item['captionText']?></p>
                                </div>
                            </div>
                        <? endforeach ?>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#<?=$carouselId?>" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#<?=$carouselId?>" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5">
                <? if ($GLOBALS['locale'] == 'de') : ?>
                    <p>Vom 01. -03. Mai 2015 ist es wieder so weit, der Billardsportverein Playhouse FFB veranstaltet die zweiten Playhouse Actiondays Fürstenfeldbruck.</p>
                    <p>Wie auch schon bei den ersten Actiondays im November 2013 werden wieder internationale Stars, darunter auch amtierende Welt- und Europameister mit dabei sein und dem Turnier ein internationales Flair verleihen.</p>
                    <p>Insgesamt wird das Turnier 64 Teilnehmer plus 16 gesetzte Topspieler aus der europäischen Elite umfassen. Außerdem erwähnenswert, das Gesamtpreisgeld von 9.000 €.</p>
                    <p>Neben dem Hauptturnier wird es noch zahlreiche weitere Billard-Highlights geben: Am Samstag, den 02. Mai 2015 wird ab 12 Uhr der „Nation-Cup“ ausgetragen. Dieser ist an den legendären, weltweit bekannten World Cup of Pool angelehnt und verspricht durch 8 Teams mit je zwei National-Spielern, Billard vom Feinsten. Die Spieler vertreten bei diesem Turnier ihr jeweiliges Heimatland und versuchen sich das Preisgeld von insgesamt 2.000 € zu sichern.</p>
                <? else : ?>
                    <p>From 1–3 May 2015, BSV Playhouse FFB hosts the second Playhouse Actiondays in Fürstenfeldbruck.</p>
                    <p>Like the first Actiondays in November 2013, international stars, including World and European champions will give the tournament a special flair.</p>
                    <p>The tournament will include 64 players. Additionally, 16 seeded players from the European elite will participate. The prize money is € 9.000.</p>
                    <p>There will be a lot more billard highlights in addition to the main event: On Saturday, the 2nd of May, at 12 p.m., the „Nation Cup“ will be held. It is inspired by the legendary, worldwide known World Cup of Pool. The event promises billard at its best with 8 teams having 2 national players each. The players representing their home country will try to secure the prize money of € 2.000.</p>
                <? endif ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <? if ($GLOBALS['locale'] == 'de') : ?>
                    <p>Das Alleinstellungsmerkmal der ActionDays sind die MoneyMatches. So können auch dieses Jahr am Freitag und Samstag ab 18 Uhr MoneyMatches gespielt werden. An diesen kann jeder teilnehmen und sich vor Ort einen Spielpartner suchen. </p>
                    <p>Auch bei den diesjährigen ActionDays wird am Samstag, parallel zum Billardturnier, ein Pokerturnier veranstaltet. An diesem Event kann ebenfalls jeder teilnehmen.</p>
                    <p>Eines der Highlights wird zweifelsohne das MoneyMatch am Freitag Abend um 20 Uhr mit der Schweizer Nr. 1 Dimitri Jungo, am Freitag Abend um 20 Uhr sein. Dieses findet in der eigens für solche Veranstaltungen gebauten ActionArena mit zwei Zuschauertribünen, einem Technik-Podest und einem Pool-Tisch statt. Wer als Gewinner aus diesem Match hervorgeht, wird sich nicht nur die Anerkennung zahlreicher Zuschauer sichern, zusätzlich gibt es auch noch 2.000 €.</p>
                    <p>Das Feedback von Simon D’Vali, eine feste Größe im internationalen Billardsport und Betreuer des Team England 2013, bei den ersten Playhouse ActionDays Fürstenfeldbruck sagt alles.</p>
                    <p><i>„The courtesy, hospitality and love the English Team were shown was beyond measure and has completely overwhelmed us. We were all collected at the airport like superstars and taken to the hotel which was yards from the venue where we were playing. The club itself is a really fine place that clearly looks after the players. The Arena…..well…..look at the pictures. The atmosphere during the matches was borderline fanatical.“</i></p>
                    <p>Allein diese Aussage zeigt, dass sich ein Besuch bei den zweiten Playhouse ActionDays 2015 in Fürstenfeldbruck lohnt. Dieses Turnier besticht nicht nur durch die hohe Zahl an internationalen Stars, sondern auch durch eine fantastische, atemberaubende Atmosphäre.</p>
                    <p>Wir freuen uns auf euren Besuch.</p>
                <? else :?>
                    <p>The MoneyMatches are the emotional selling propositions of the Actiondays. For the first time this year, everbody is allowed to take part at these suspense-packed matches. The MoneyMatches start at 6 p.m on Saturday and Sunday.</p>
                    <p>Also this year, a poker tourrnament will take place parallel to the billard tournament. Everyone is welcome to join the poker event.</p>
                    <p>One of the highlights is the MoneyMatch of the Swiss number one player, Dimitri Jungo, on Friday evening, at 8 p.m. This event will be held in the specially constructed ActionArena with two grand stands. Who will win this MoneyMatch is not only going to receive recognition, but a prize money of € 2.000.</p>
                    <p>The feedback of Simon D’Vali, a constant in the international billard sport and carer of Team England at the first Actiondays 2013, says it all:</p>
                    <p><i>„The courtesy, hospitality and love the English Team were shown was beyond measure and has completely overwhelmed us. We were all collected at the airport like superstars and taken to the hotel which was yards from the venue where we were playing. The club itself is a really fine place that clearly looks after the players. The Arena…..well…..look at the pictures. The atmosphere during the matches was borderline fanatical.“</i></p>
                    <p>This statement alone shows that the Actiondays is worth a visit. The tournament does not only bring together a high number of international players, but also guarantees a fantastic and stunning atmosphere.</p>
                    <p>We are looking forward to your visit.</p>
                <? endif?>
            </div>
        </div>
    </div>
</section>
