<?php
$tabs = $data['tabs'];
$activeTab =$data['activeTab'];
?>
<section id="info">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('info.title')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <div class="portfolio-filter">
                    <ul id="filters" class="clearfix">
                        <? foreach ($tabs as $name => $tab) : ?>
                            <li>
                                <a href="?section=info&tab=<?=$name?>">
                                    <span class="filter<?=$activeTab == $name ? ' active' : ''?>" data-filter="<?=$name?>"><?=translate('tab.' . $name)?></span>
                                </a>
                            </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="<?=$activeTab?>" class="text-left">
            <? $data = $tabs[$activeTab] ?>
            <div class="content active" data-cat="<?=$activeTab?>" data-toggle="modal">
                <? include("info/{$activeTab}.phtml") ?>
            </div>
        </div>
    </div>
</section>
