<?php
$tabs = $data['tabs'];
$activeTab =$data['activeTab'];
?>
<section id="participants">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('participants.title')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <div class="slider-buttons portfolio-filter">
                    <ul id="filters" class="clearfix">
                        <? foreach ($tabs as $name => $tab) : ?>
                            <li>
                                <a href="?section=participants&tab=<?=$name?>">
                                    <span class="filter<?=$activeTab == $name ? ' active' : ''?>" data-filter="<?=$name?>"><?=translate('tab.' . $name)?></span>
                                </a>
                            </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="sliderlist">
            <? $data = $tabs[$activeTab] ?>
                <div class="content active" data-cat="<?=$activeTab?>" data-toggle="modal">
                    <? include("participants/{$activeTab}.phtml") ?>
                </div>
        </div>
        <div id="loaded-content"></div>
        <button href="#" class="red-btn" id="back-button"><i class="icon-fontawesome-webfont-27"></i> Go Back</button>
    </div>
</section>
