<?php
$tabs = $data['tabs'];
$activeTab =$data['activeTab'];
?>
<section id="participants">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('participants.title')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <div class="slider-buttons portfolio-filter">
                    <ul id="filters" class="clearfix">
                        <? foreach ($tabs as $name => $tab) : ?>
                            <li>
                                <span class="filter<?=$activeTab == $name ? ' active' : ''?>" data-filter="<?=$name?>"><?=translate('tab.' . $name)?></span>
                            </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="sliderlist">
            <? foreach($tabs as $name => $dataPartial) : ?>
                <div class="content <?=$name?> <?=$activeTab == $name ? 'active' : ''?>" data-cat="<?=$name?>>" data-toggle="modal">
                    <? $data = $dataPartial?>
                    <? include("participants/{$name}.phtml") ?>
                </div>
            <? endforeach ?>
        </div>
    </div>
</section>
