<?php
if (isset($data['valid']) && $data['valid'] === true) {
    $renderForm = false;
} else {
    $renderForm = true;
}
?>
<section id="registration">
    <div class="container text-center wow fadeIn animated animated">
        <? if ($renderForm) : ?>
            <? include("registration/form.phtml") ?>
        <? else : ?>
            <? include("registration/success.phtml") ?>
        <? endif ?>
    </div>
</section>
