<?php
if (isset($data['valid']) && $data['valid'] === true) {
    $renderForm = false;
} else {
    $renderForm = true;
}
?>
<section id="registration">
    <div class="container text-center wow fadeIn animated animated">
        <? if ($renderForm) : ?>
            <? include("registration/form.phtml") ?>
        <? else : ?>
        <div class="success">
            <div class="row">
                <h2><?=translate('registration.success.title')?></h2>
                <div class="col-lg-12 text-center">
                    <hr class="colored">
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-8 col-md-offset-2">
                    <? include("registration/success_{$GLOBALS['locale']}.phtml") ?>
                </div>
            </div>
        </div>
        <? endif ?>
    </div>
</section>
