<?php
$pathTo = IMG_PATH . 'sponsors/';
$sponsors = [
    [
        'name' => 'Playhouse Fürstenfeldbruck',
        'website' => 'playhouse-ffb.de',
        'imgUrl' => $pathTo . 'Playhouse.png'
    ],
    [
        'name' => 'German Tour 2015',
        'website' => 'touch-magazine.net/index.php/german-masters/touch-german-tour',
        'imgUrl' => $pathTo . 'German_Tour_2015.jpg'
    ],
    [
        'name' => 'K Getränkemarkt',
        'website' => 'k-getraenkemarkt.de/',
        'imgUrl' => $pathTo . 'K_Getraenkemarkt.jpg'
    ],
    [
        'name' => 'Arcaden Casinos',
        'website' => 'arcaden-casinos.de/',
        'imgUrl' => $pathTo . 'Arcaden_Casinos.png'
    ],
    [
        'name' => '4MS - Martin Schröder',
        'website' => '4ms-pool-cues.de/index.html',
        'imgUrl' => $pathTo . 'logo_4MS.png'
    ],
    [
        'name' => 'Flyerdruck',
        'website' => '#',
        'imgUrl' => $pathTo . 'Flyerdruck.png'
    ],
]
?>
<section id="info">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('sponsors.title')?></h2>
        <hr class="colored">
        <div class="information-details">
            <?foreach($sponsors as $sponsor) : ?>
            <div class="row text-center">
                <div class="col-md-4 col-md-offset-2">
                    <h3><?=$sponsor['name']?></h3>
                </div>
                <div class="col-md-4">
                    <a href="http://<?=$sponsor['website']?>" target="_blank">
                        <img style="max-width: 100%" src="<?=$sponsor['imgUrl']?>" alt="<?=$sponsor['name']?>" />
                    </a>
                </div>
            </div>
            <?endforeach?>
        </div>
    </div>
</section>
