<h2>404 Not Found</h2>
<hr class="colored">
<div class="row commingsoon text-center">
    <div class="col-md-12">
        <h3 class="blue-text"><?=translate('error.page.hint.404')?></h3>
        <a href="/index.php">
            <h2 class="caption blue-text"><?=translate('link.to.homepage')?></h2>
            <img  width="100%" src="<?=IMG_PATH . 'bg_arena_sw.jpg'?>"/>
        </a>
    </div>
</div>
