<div class="alert alert-success">
    <div class="row">
        <div class="col-sm-1 col-xs-12"><i class="fa fa-thumbs-up">&nbsp;</i></div>
        <div class="col-sm-10 col-xs-12"><strong>Your registration has been received</strong></div>
        <div class="col-sm-1 hidden-xs"><i class="fa fa-thumbs-up">&nbsp;</i></div>
    </div>
</div>
<div class="alert alert-danger">
    <p><strong>We point out that the registration is only secured after payment of the entry fee</strong></p>
</div>
<div class="alert alert-success text-left">
    <p><strong>Entry fee:</strong><br>
        60 € cash receipt till April 27th 2015<br>
        80 € cash receipt from April 28th 2015</p>
    <p><strong>Bank account:</strong><br>
        BSV Playhouse Fürstenfeldbruck e.V.<br>
        Account-No.: 31817885<br>
        IBAN: DE59700530700031817885<br>
        Bank: Sparkasse Fürstenfeldbruck</p>
    <p>Please provide your name and the group wish (Friday or Saturday + starting time)</p>
    <p>Soon you will receive a confirmation email with all the details.</p>
</div>
