<div class="alert alert-success">
    <div class="row">
        <div class="col-sm-1 col-xs-12"><i class="fa fa-thumbs-up">&nbsp;</i></div>
        <div class="col-sm-10 col-xs-12"><strong>Deine Anmeldung ist bei uns eingegangen</strong></div>
        <div class="col-sm-1 hidden-xs"><i class="fa fa-thumbs-up">&nbsp;</i></div>
    </div>
</div>
<div class="alert alert-danger">
    <p><strong>Wir weisen darauf hin, dass der Startplatz erst nach Geldeingang gesichert ist!</strong></p>
</div>
<div class="alert alert-success text-left">
    <p><strong>Das Startgeld:</strong><br>
    60 € bei Geldeingang bis 27.04.2015<br>
    80 € bei Geldeingang ab 28.04.2015</p>
    <p><strong>Kontoverbindung:</strong><br>
    BSV Playhouse Fürstenfeldbruck e.V.<br>
    Konto Nr.: 31817885<br>
    IBAN: DE59700530700031817885<br>
    Sparkasse Fürstenfeldbruck</p>
    <p>Bei der Überweisung bitte Name, Gruppe (Freitag oder Samstag) und Uhrzeit angeben.</p>
    <p>In Kürze erhälst Du eine Bestätigungsmail mit allen Details.</p>
</div>
