<div class="information-details">
    <div class="row">
        <div class="col-md-4">
            <strong>Participants:</strong>
        </div>
        <div class="col-md-8">
            <p>8 countries represented by 2 players</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>When:</strong>
        </div>
        <div class="col-md-8">
            <p>Saturday, 2 Mai, 2015</p>
            <p>First match: 12 pm</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Playing mode:</strong>
        </div>
        <div class="col-md-8">
            <p>10 Ball</p>
            <p>Scotch doubles, Single Elimination</p>
            <p>Race to 7, winnerbreak</p>
            <p>Shot Clock 35(10) seconds</p>
            <p>All matches will be played in the Playhouse Action Arena.</p>
            <p>Navigate to <a href="?section=results&tab=friday">Draw / Results</a> to see start times of all Nation`s Cup matches.</p>
        </div>
    </div>
    <?php
    $priceMoney = [
        'Winner'    => '1.000,00',
        'Runner-up' => '500,00',
        '3 - 4'     => '250,00',
    ]
    ?>
    <div class="row">
        <div class="col-md-4">
            <strong>Price money:</strong>
        </div>
        <div class="col-md-8">
            <div class="row">
                <? foreach ($priceMoney as $place => $price) : ?>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                        <?=$place?>:
                    </div>
                    <div class="col-xs-6 col-sm-8 col-md-9">
                        <?=$price?>
                    </div>
                <? endforeach ?>
            </div>
        </div>
    </div>
</div>

