<?php
$countries = $data['countries'];
$imgHeight = '33%';
?>

<div class="row text-center margin-top margin-bottom">
    <? foreach($countries as $countryCode => $countryData) : ?>
        <div class="col-md-6">
            <div class="countryTeam">
                <img title="<?=$countryData['player1']['firstname'] . ' ' . $countryData['player1']['surname']?>" width="24%" src="<?=IMG_PATH . 'seeded/' . $countryData['player1']['surname'] . '_thumbnail.jpg'?>" alt="<?=$countryData['player1']['firstname'] . ' ' . $countryData['player1']['surname']?>">
                <img title="<?=translate('country.' . $countryCode)?>" width="42%" src="<?=IMG_PATH . 'wcop/participants/' . $countryCode . '_thumbnail.jpg'?>" alt="<?=translate('country.' . $countryCode)?>">
                <img title="<?=$countryData['player2']['firstname'] . ' ' . $countryData['player2']['surname']?>" width="24%" src="<?=IMG_PATH . 'seeded/' . $countryData['player2']['surname'] . '_thumbnail.jpg'?>" alt="<?=$countryData['player2']['firstname'] . ' ' . $countryData['player2']['surname']?>">
            </div>
        </div>
    <?endforeach?>
</div>
