<section id="login">
    <div class="container text-center wow fadeIn animated">
        <h2><?=translate('LOGIN')?></h2>
        <hr class="colored">
        <div class="row content-row">
            <div class="col-lg-12">
                <form action="?section=login" class="form-horizontal" method="post">
                    <fieldset>
                        <label>Benutzername: <input type="text" name="Username" /></label>
                        <label>Password: <input type="password" name="Password" /></label>
                        <input type="submit" name="formaction" value="Einloggen" />
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</section>
