<div class="information-details">
    <div class="row">
        <div class="col-md-4">
            <strong>Teilnehmerzahl:</strong>
        </div>
        <div class="col-md-8">
            <a href="?section=participants&tab=main_tournament">64 Teilnehmer</a>
            +
            <a href="?section=participants&tab=seeded">16 gesetzte Top Spieler</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Startzeiten der Qualifikationsgruppen:</strong>
        </div>
        <div class="col-md-8">
            <p>
                32er Feld am Freitag 01.05.2015<br>
                Gruppe 1: 16 Spieler um 10 Uhr (4 Qualifikanten)<br>
                Gruppe 2: 16 Spieler um 12 Uhr (4 Qualifikanten)
            </p>
            <p>
                32er Feld am Samstag 02.05.2015<br>
                Gruppe 3: 16 Spieler um 10 Uhr (4 Qualifikanten)<br>
                Gruppe 4: 16 Spieler um 12 Uhr (4 Qualifikanten)
            </p>
            <p>
                Startzeiten der einzelnen Partien sind unter <a href="?section=results&tab=friday">Auslosung / Ergebnisse</a> zu sehen.
                <br>
                Anwesenheitspflicht ist jeweils 30 Min. vor Startzeit.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Spielmodus über das gesamte Turnier:</strong>
        </div>
        <div class="col-md-8">
            <p>
                Einfach-KO<br>
                10Ball<br>
                Best of 3 Sätze<br>
                Je Satz race to 5<br>
                Winnerbreak nach Regeln der WPA: <a href="http://wpa-pool.com" target="_blank">www.wpa-pool.com</a>
            </p>
            <p>
                16 Spieler qualifizieren sich für die <strong>Knock-Out-Challenge</strong>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Knock-Out-Challenge:</strong>
        </div>
        <div class="col-md-8">
            <p>Sonntag, 03.05.2015</p>
            <p>Anstoß um 10 Uhr</p>
            <p>16 gesetzte Top Spieler + 16 Qualifikanten</p>
            <p>Anwesenheitspflicht ist jeweils 30 Min. vor Startzeit.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Dresscode:</strong>
        </div>
        <div class="col-md-8">
            Es wird auf ein gepflegtes Erscheinungsbild Wert gelegt.
        </div>
    </div>
    <?php
    $priceMoney = [
        'Winner'    => '2.000,00',
        'Runner-up' => '1.000,00',
        '3 - 4'     => '500,00',
        '5 - 8'     => '350,00',
        '9 - 16'    => '250,00',
        '17 - 32'   => '100,00'
    ]
    ?>
    <div class="row">
        <div class="col-md-4">
            <strong>Preisgeld:</strong>
        </div>
        <div class="col-md-8">
            <div class="row">
                <? foreach ($priceMoney as $place => $price) : ?>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                        <?=$place?>:
                    </div>
                    <div class="col-xs-6 col-sm-8 col-md-9">
                        <?=$price?> €
                    </div>
                <? endforeach ?>
            </div>
            <p class="margin-top">Die Einnahme von Preisgeld ist steuerpflichtig.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Anmeldung:</strong>
        </div>
        <div class="col-md-8">
            Die Anmeldung erfolgt über das <a href="?section=registration">Anmeldeformular</a> oder vor Ort und verpflichtet zur Zahlung des Startgeldes.
            <br><br>
            <p class="text-center alert alert-danger">Der Startplatz wird erst durch Geldeingang reserviert.</p>
            Bei Abmeldung nach Geldeingang wird das Startgeld zurückerstattet, wenn das gewählte Feld komplett besetzt ist.
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Startgebühr:</strong>
        </div>
        <div class="col-md-8">
            60 € bei Geldeingang bis 27.04.2015
            <br>
            80 € bei Geldeingang ab 28.04.2015
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Konto:</strong>
        </div>
        <div class="col-md-8">
            BSV Playhouse Fürstenfeldbruck e.V.
            <br>
            Bank: Sparkasse Fürstenfeldbruck
            <br>
            Konto Nr.: 31817885
            <br>
            IBAN: DE59700530700031817885
            <br>
            BIC: BYLADEM1FFB
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>DBU - Genehmigungsnummer:</strong>
        </div>
        <div class="col-md-8">
            DBU-10-Ball-003-2015
        </div>
    </div>
    <div class="alert alert-danger text-center">
        ACHTUNG WICHTIGER HINWEIS!!!<br>
        Aufgrund von Terminüberschneidungen wird zum gleichen Zeitpunkt ein Damen Grand Prix der DBU stattfinden. Deshalb ist die Teilnahme von Damen seitens der DBU nicht genehmigt worden. Darauf haben wir leider keinen Einfluss!
        Es steht aber natürlich jeder Dame frei an unserem Abendevent (ActionNights) teilzunehmen. Diese zählen nicht zum ActionDays Turnier.
    </div>
    <div class="alert alert-danger margin-top text-center">
        <?=translate('registration.media.confirmation')?>
    </div>
</div>
