<div class="information-details">
    <div class="row">
        <div class="col-md-4">
            <strong>Participants</strong>
        </div>
        <div class="col-md-8">
            <a href="?section=participants&tab=main_tournament">64 Teilnehmer</a>
            +
            <a href="?section=participants&tab=seeded">16 seeded Top Players</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <strong>Start times of the qualification rounds</strong>
        </div>
        <div class="col-md-8">
            <p>
                32 players on friday, Mai 01, 2015<br>
                Group 1: 16 players at 10 am (4 qualifiers)<br>
                Group 2: 16 players at 12 noon (4 qualifiers)
            </p>
            <p>
                32 players on saturday, Mai 02, 2015<br>
                Group 3: 16 players at 10 am (4 qualifiers)<br>
                Group 4: 16 players at 12 noon (4 qualifiers)
            </p>
            <p>
                Navigate to <a href="?section=results&tab=friday">Draw / Results</a> to see start times of all matches.
                <br>
                Compulsary attendance is 30 min. before starting time.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Playing mode through the whole tournament</strong>
        </div>
        <div class="col-md-8">
            <p>
                10 Ball<br>
                single elimination, 2 winning sets<br>
                each set is a race to 5<br>
                winnerbreak by rules of WPA: <a href="http://wpa-pool.com">www.wpa-pool.com</a>
            </p>
            <p>
                16 players qualify for the <strong>Knock-Out-Challenge</strong>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Knock-Out-Challenge</strong>
        </div>
        <div class="col-md-8">
            <p>Sunday, 03 May, 2015</p>
            <p>16 seeded players + 16 qualifiers</p>
            <p>First round (last 32): 10 am</p>
            <p>Compulsary attendance is 30 min. before starting time.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Dresscode</strong>
        </div>
        <div class="col-md-8">
            Value is put on a neat appearance.
        </div>
    </div>

    <?php
    $priceMoney = [
        'Winner'    => '2.000,00',
        'Runner-up' => '1.000,00',
        '3 - 4'     => '500,00',
        '5 - 8'     => '350,00',
        '9 - 16'    => '250,00',
        '17 - 32'   => '100,00'
    ]
    ?>
    <div class="row">
        <div class="col-md-4">
            <strong>Price money</strong>
        </div>
        <div class="col-md-8">
            <div class="row">
                <? foreach ($priceMoney as $place => $price) : ?>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                        <?=$place?>:
                    </div>
                    <div class="col-xs-6 col-sm-8 col-md-9">
                        <?=$price?>
                    </div>
                <? endforeach ?>
            </div>
            <p class="margin-top">Receipt of prize money is taxable.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Registration</strong>
        </div>
        <div class="col-md-8">
            The registration has to be done via the registration form or on location at the tournament management.
            Registration obligates to payment of the starting fee.
            <br><br>
            <p class="text-center alert alert-danger">The starting place will be reserved not until money receipt. </p>
            In case of deregistration after payment the registration fee will be refunded if the chosen field is completely filled.
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Entry fee</strong>
        </div>
        <div class="col-md-8">
            60 EUR with receipt until April 27, 2015
            <br>
            80 EUR with receipt from April 28, 2015
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <strong>Bank account:</strong>
        </div>
        <div class="col-md-8">
            BSV Playhouse Fürstenfeldbruck e.V.
            <br>
            Account No.: 31817885
            <br>
            IBAN: DE59700530700031817885
        </div>
    </div>

    <div class="alert alert-danger margin-top text-center">
        <?=translate('registration.media.confirmation')?>
    </div>
</div>
