<?php
/**
 * 'players' = []
 */
?>
<section id="participants">
    <div class="container text-center wow fadeIn animated">
        <table class="table table-hover text-left">
            <thead>
            <tr>
                <th><?=translate('table.lable.firstname')?></th>
                <th><?=translate('table.lable.surname')?></th>
                <th><?=translate('table.lable.country')?></th>
                <th class="text-center"><?=translate('table.lable.register_status')?></th>
                <th class="text-right"><?=translate('table.lable.startday')?></th>
                <th class="text-right"><?=translate('table.lable.starttime')?></th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($data['players'] as $player) : ?>
                <tr>
                    <td><?=$player['firstname']?></td>
                    <td><?=$player['surname']?></td>
                    <td><?=translate("country." . mb_strtolower($player['country_code']) . "")?></td>
                    <td class="text-center">
                        <span class="label label-<?=$player['registration_status'] == 'confirmed' ? 'success' : 'danger'?>">
                            <?=translate("player.register_status." . $player['registration_status'])?></span></td>
                    <td class="text-right"><?=$player['start_day']?></td>
                    <td class="text-right"><?=$player['start_time']?></td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
</section>

<section>
    <div class="container">
        <div style="height: 807px">
            <object data="assets/pdf/ActionDays2013_Auslosung_Freitag.pdf" type="application/pdf" width="100%" height="100%"></object>
        </div>
    </div>
</section>
