<?php
?>
<div class="row projects">
    <div id="loader" style="display: none;">
        <div class="loader-icon"></div>
    </div>
    <div class="col-md-12" id="portfolio-list" style="margin-left: 0px; display: block;">
        <!-- PLAYER ITEMS-->
        <ul class="cbp-rfgrid">
            <? foreach($data['players'] as $player) : ?>
                <?$playerFullName = "{$player['firstname']}  {$player['nickname']} {$player['surname']}"?>
                <li class="zoomIn animated" style="visibility: visible;-webkit-animation-duration: 1.5s; -moz-animation-duration: 1.5s; animation-duration: 1.5s;-webkit-animation-delay: 0.15s; -moz-animation-delay: 0.15s; animation-delay: 0.15s;">
                    <a target="_blank" href="" class="more">
                        <img src="<?=IMG_PATH . "seeded/" . $player['surname'] . '.png'?>" alt="<?=$playerFullName?>">
                        <div class="project-info">
                            <div class="project-details">
                                <? if($player['surname'] != 'unknown') : ?>
                                    <h5 class="white-text red-border-bottom">
                                        <?=$playerFullName?>
                                    </h5>
                                    <div class="details white-text">
                                        <?=translate("country." . mb_strtolower($player['country_code']) . "")?>
                                    </div>
                                <?else:?>
                                    <h5>COMMING SOON</h5>
                                <?endif?>
                            </div>
                        </div>
                    </a>
                </li>
            <? endforeach ?>
        </ul>
    </div>
    <!-- END OF PORTFOLIO ITEMS-->
</div>
