<?php
$videos = [
    'https://www.youtube.com/embed/eiqAYW6HrkI',
    'https://www.youtube.com/embed/LtvXycuGgoU',
    'https://www.youtube.com/embed/OZ2HJb5c0GM',
    'https://www.youtube.com/embed/XD32Naf8h2U',
    'https://www.youtube.com/embed/BpW-1geY3z0',
    'https://www.youtube.com/embed/_ksq9HNUxa4',
    'https://www.youtube.com/embed/e8L3ZqilUzo',
    'https://www.youtube.com/embed/1YGLZ3Q3VGI',
    'https://www.youtube.com/embed/aSmwuCG2at0',
    'https://www.youtube.com/embed/Q2WBXnqBIAU',
    'https://www.youtube.com/embed/_uQM_ob8GtU',
]
?>
<div class="row">
    <?foreach($videos as $video):?>
        <div class="col-md-6">
            <iframe width="100%" height="300"
                    src="<?=$video?>"
                    frameborder="0"
                    allowfullscreen>
            </iframe>
        </div>
    <?endforeach?>
</div>
